# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59e094f455d335118f4dc654124eda19efd1b0d174c9a9824e68460af5f3197a241e94d4232c68d7439e7a293a5eb5cda3b5deb00cb60f2f17d290cfdd985cc8

test:
  secret_key_base: cd616594c395e8c831e832a44671adc3e2cd290411e9014e4fff655f3536cccfb3fe19ee299d8b2fe2404ffb5b39788cd48c6c65be67c718deb62319bec7537c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
